In [1]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],  # Student 1
    [19, 92, 88],  # Student 2
    [17, 76, 95],  # Student 3
    [18, 65, 70],  # Student 4
    [20, 90, 85]   # Student 5
])

Get The Shape of the Matrix

In [2]:
data.shape

(5, 3)

Find the Average of Age of Students


In [3]:
np.mean(data[:, 0])

np.float64(18.4)

Extract Math Marks of All Students

In [4]:
data[:, 1]

array([85, 92, 76, 65, 90])

Find the Highest Science Marks


In [5]:
np.max(data[:, 2])

np.int64(95)

Get Details of Student who Scored more than 90 Marks in Math


In [6]:
data[data[:, 1] > 90]

array([[19, 92, 88]])

Increase Math Marks of all Students by 5


In [7]:
data[:, 1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

Find How many Students are Younger than 19


In [8]:
len(data[data[:, 0] < 19])

3

Calculate Average Marks in each Subject

In [9]:
print("Average Math Marks:", np.mean(data[:, 1]))
print("Average Science Marks:", np.mean(data[:, 2]))

Average Math Marks: 86.6
Average Science Marks: 83.2


Get the Data of Students who Scored atleast 80 in both Subjects


In [10]:
data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

Replace all Science Marks < 75 with 0

In [11]:
data[:, 2][data[:, 2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])